### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by zircothc** [copych/ESP32_S3_Sampler#2]
Hi.
Some time ago I downloaded your project but I was busy and I didn't test it.
Now I've downloaded your current version but I can't compile. Lots of errors in voice.h
The old versión compiles ok.
[errors.txt](https://github.com/copych/ESP32_S3_Sampler/files/15473605/errors.txt)
I dont know if this is a "boards" versión issue,. I've tested with three different "boards" versions.
This project is amazing. I'm thinking about building an e-drum module.
Thank you.

**Comment by copych** [comment]
@zircothc Sorry for that, it seems that versions mixed somehow.
I am working on the next iteration, so hopefully in a couple of days there'll be a new version.
I got rid of multiple functions for different bit depths, cleaned some code, but the sampler still suffers of clicks on overrunning max polyphony.

**Comment by copych** [comment]
@zircothc  I have just uploaded a more or less stable version, please, try

**Comment by zircothc** [comment]
Hey thank you.
I'll try in a moment.
;)

**Comment by zircothc** [comment]
Hi.
Compiles OK.
And...wow... it sounds amazing.
Thank you @copych
